import { Container, Title, Accordion, Paper, Text, Code } from '@mantine/core';
import classes from './About.module.css';
import { Link } from 'react-router-dom';

const placeholder =
    ["For those enrolled in CENG482 Introduction to Computer Security course and for anyone interested.",
        "You can access course content generated by ChatGPT from the \"Learn\" section. \
        Course content consists of learning outcomes, slides, quizzes, and a feedback form. \
        If you register, you can track your progress.",
        "For any further questions contact me or "]

export default function About() {

    const gptLink = <a href="https://chat.openai.com/g/g-O6ZtTDjLi-cyber-gazi" target="_blank" rel="noopener noreferrer">ask our GPT</a>
    return (
        <Container size="sm" className={classes.wrapper}>
            <Title ta="center" className={classes.title}>
                Who are we?
            </Title>
            <Paper p="xl">
                <Text size='md' c="dimmed">
                    This website is being developed within the scope of Computer Project I & II
                    courses under the leadership of Prof. Dr. Şeref Sağıroğlu. Our team consists of one person: Ayşenur Yavaşoğlu
                </Text>
                <Text size='md' c="dimmed">
                    Contact me: <Code>aysenur.yavasoglu@gazi.edu.tr</Code>
                </Text>

            </Paper>

            <Accordion variant="separated">
                <Accordion.Item className={classes.item} value="reset-password">
                    <Accordion.Control>Who is this course for?</Accordion.Control>
                    <Accordion.Panel>{placeholder[0]}</Accordion.Panel>
                </Accordion.Item>

                <Accordion.Item className={classes.item} value="another-account">
                    <Accordion.Control>How can I benefit from this platform?</Accordion.Control>
                    <Accordion.Panel>{placeholder[1]}</Accordion.Panel>
                </Accordion.Item>

                <Accordion.Item className={classes.item} value="newsletter">
                    <Accordion.Control>Whom should I contact for my questions?</Accordion.Control>
                    <Accordion.Panel>{placeholder[2]} {gptLink}</Accordion.Panel>
                </Accordion.Item>
            </Accordion>
        </Container>
    );

}
